include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: error
    unused_local_variable: error
    dead_code: error

linter:
  rules:
    # Performance & const
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true

    # Clean code
    prefer_final_locals: true
    prefer_final_fields: true
    unnecessary_this: true
    avoid_redundant_argument_values: true

    # Readability
    always_use_package_imports: true
    require_trailing_commas: true
    curly_braces_in_flow_control_structures: true

    # Safety
    use_key_in_widget_constructors: true
    avoid_null_checks_in_equality_operators: true

    # Best practices
    avoid_function_literals_in_foreach_calls: true
    avoid_positional_boolean_parameters: true

    # Style
    prefer_single_quotes: true
