// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_sw47htftQe72oIyAbHLsViVG7sVPyrM',
    appId: '1:674635070625:web:fcc222e63d08587e68c4e0',
    messagingSenderId: '674635070625',
    projectId: 'full-e-commerce-998b4',
    authDomain: 'full-e-commerce-998b4.firebaseapp.com',
    databaseURL: 'https://full-e-commerce-998b4-default-rtdb.firebaseio.com',
    storageBucket: 'full-e-commerce-998b4.firebasestorage.app',
    measurementId: 'G-H23BBHJX4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMl50vjJQuXeTcNtboM3XjJQs4q1-aDLA',
    appId: '1:674635070625:android:b50db041870a311368c4e0',
    messagingSenderId: '674635070625',
    projectId: 'full-e-commerce-998b4',
    databaseURL: 'https://full-e-commerce-998b4-default-rtdb.firebaseio.com',
    storageBucket: 'full-e-commerce-998b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfA85J8Bm4lJZhwTy00mUtCpHWdWLr8oA',
    appId: '1:674635070625:ios:510b146e74f3214c68c4e0',
    messagingSenderId: '674635070625',
    projectId: 'full-e-commerce-998b4',
    databaseURL: 'https://full-e-commerce-998b4-default-rtdb.firebaseio.com',
    storageBucket: 'full-e-commerce-998b4.firebasestorage.app',
    iosClientId: '674635070625-4ksco3eajhnt15ql0ecst6459jqls029.apps.googleusercontent.com',
    iosBundleId: 'com.example.ppp',
  );
}
